title: 福岡県久留米市
description: 福岡県久留米市内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1SzEc-oIjgIbUPxDJmttyiMNcFsOT3kUx75YuOUGyunc/export?format=csv&gid=942945321
repository: https://github.com/iemeshi/app/
form_url: https://docs.google.com/forms/d/1baLoinARW8nlh-xdVeXnPKZWzqGtD11KdpVhWnzz0dM/viewform
